import { useEffect, useState } from "react";
import {
  fetchActionablePurchaseOrders,
  advancePurchaseOrder,
  cancelPurchaseOrder,
  fetchPurchaseOrderPdf,
} from "../../api/purchaseOrderApi.js";
import { downloadBlob } from "../../utils/downloadBlob.js";

// Reuses the app's existing status-color tokens across a different domain, the
// same way ItemCard already does for LOW_STOCK - not a new palette, just borrowing
// the "needs attention" (amber) / "in progress" (blue/purple) associations.
const STATUS_STYLES = {
  DRAFT: { label: "Draft", classes: "bg-slate-500/20 text-slate-300" },
  PENDING_APPROVAL: { label: "Pending Approval", classes: "bg-status-cleaning/20 text-status-cleaning" },
  APPROVED: { label: "Approved", classes: "bg-status-billed/20 text-status-billed" },
  ORDERED: { label: "Ordered", classes: "bg-status-reserved/20 text-status-reserved" },
};

const ADVANCE_LABEL = {
  DRAFT: "Send for Approval",
  PENDING_APPROVAL: "Approve",
  APPROVED: "Mark Ordered",
};

function formatCurrency(value) {
  return `LKR ${Number(value ?? 0).toLocaleString("en-LK", { maximumFractionDigits: 0 })}`;
}

function lineEstimate(item) {
  return Number(item.quantityOrdered) * Number(item.estimatedUnitCost ?? 0);
}

export default function PoApprovalPanel({ highlightPoId }) {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState(null);
  const [error, setError] = useState(null);

  const load = () => {
    fetchActionablePurchaseOrders()
      .then(setOrders)
      .finally(() => setLoading(false));
  };

  useEffect(load, []);

  // Figure 3.10: a stock alert's "direct link to the auto-drafted PO" - re-fetch so a
  // PO drafted after this panel's initial load is guaranteed present before scrolling.
  useEffect(() => {
    if (highlightPoId) load();
  }, [highlightPoId]);

  useEffect(() => {
    if (highlightPoId && orders.some((po) => po.id === highlightPoId)) {
      document.getElementById(`po-row-${highlightPoId}`)?.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }, [highlightPoId, orders]);

  const runAction = async (id, action) => {
    setBusyId(id);
    setError(null);
    try {
      const updated = await action(id);
      // ORDERED has no further advance step surfaced here (RECEIVED happens via the
      // GRN receipt flow), so once an order reaches ORDERED it stays visible read-only;
      // CANCELLED drops out of the actionable list entirely.
      if (updated.status === "CANCELLED") {
        setOrders((prev) => prev.filter((po) => po.id !== id));
      } else {
        setOrders((prev) => prev.map((po) => (po.id === id ? updated : po)));
      }
    } catch (err) {
      setError(err.response?.data?.message || "Action failed - please try again.");
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div className="rounded-lg border border-ink-700 bg-ink-800 p-4">
      <div className="mb-3 flex items-center justify-between">
        <h2 className="font-display text-sm font-bold text-white">Purchase Order Approvals</h2>
        <span className="text-xs text-slate-400">{orders.length} awaiting action</span>
      </div>

      {error && (
        <div className="mb-3 rounded-lg border-l-4 border-status-occupied bg-status-occupied/10 p-2 text-xs text-status-occupied">
          {error}
        </div>
      )}

      {loading && <div className="py-6 text-center text-sm text-slate-500">Loading...</div>}

      {!loading && orders.length === 0 && (
        <div className="py-6 text-center text-sm text-slate-500">No purchase orders awaiting action.</div>
      )}

      <div className="space-y-2">
        {orders.map((po) => {
          const style = STATUS_STYLES[po.status] ?? STATUS_STYLES.DRAFT;
          const advanceLabel = ADVANCE_LABEL[po.status];
          const estimatedTotal = po.items.reduce((sum, item) => sum + lineEstimate(item), 0);
          const isBusy = busyId === po.id;

          return (
            <div
              key={po.id}
              id={`po-row-${po.id}`}
              className={`rounded-lg border bg-ink-900 p-3 transition ${
                po.id === highlightPoId ? "border-accent ring-2 ring-accent" : "border-ink-700"
              }`}
            >
              <div className="flex flex-wrap items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <span className="font-mono text-xs text-slate-500">PO-{po.id}</span>
                  <span className="text-sm font-semibold text-white">{po.supplierName}</span>
                  <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${style.classes}`}>
                    {style.label}
                  </span>
                  {po.autoGenerated && (
                    <span className="rounded-full bg-accent/20 px-2 py-0.5 text-[10px] font-medium text-accent">
                      Auto-drafted
                    </span>
                  )}
                </div>
                <span className="font-mono text-sm font-semibold text-accent">{formatCurrency(estimatedTotal)}</span>
              </div>

              <ul className="mt-2 space-y-0.5 text-xs text-slate-400">
                {po.items.map((item, i) => (
                  <li key={i}>
                    {item.ingredientName} - {Number(item.quantityOrdered).toFixed(2)} @{" "}
                    {formatCurrency(item.estimatedUnitCost)}
                  </li>
                ))}
              </ul>

              <div className="mt-3 flex items-center gap-2">
                {advanceLabel && (
                  <button
                    disabled={isBusy}
                    onClick={() => runAction(po.id, advancePurchaseOrder)}
                    className="min-h-11 rounded-full bg-accent px-3 text-xs font-semibold text-ink-950 transition hover:bg-accent-soft disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {isBusy ? "Working..." : advanceLabel}
                  </button>
                )}
                <button
                  disabled={isBusy}
                  onClick={() => runAction(po.id, cancelPurchaseOrder)}
                  className="min-h-11 rounded-full border border-ink-700 px-3 text-xs font-medium text-slate-400 transition hover:border-status-occupied hover:text-status-occupied disabled:cursor-not-allowed disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  onClick={async () => {
                    const blob = await fetchPurchaseOrderPdf(po.id);
                    downloadBlob(blob, `purchase-order-${po.id}.pdf`);
                  }}
                  className="min-h-11 px-1 text-xs font-medium text-accent hover:text-accent-soft"
                >
                  Download PDF
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
