package com.rms.service;

import com.rms.aspect.AuditableAction;
import com.rms.domain.Ingredient;
import com.rms.domain.PurchaseOrder;
import com.rms.domain.PurchaseOrderItem;
import com.rms.domain.Supplier;
import com.rms.domain.User;
import com.rms.domain.enums.PurchaseOrderStatus;
import com.rms.dto.request.CreatePurchaseOrderRequest;
import com.rms.dto.request.PurchaseOrderItemRequest;
import com.rms.dto.response.PurchaseOrderResponse;
import com.rms.exception.InvalidOrderStateException;
import com.rms.exception.ResourceNotFoundException;
import com.rms.repository.IngredientRepository;
import com.rms.repository.PurchaseOrderRepository;
import com.rms.repository.SupplierRepository;
import com.rms.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Module 2.12 - manual PO lifecycle management. Auto-drafted POs (see
 * InventoryAlertService) enter this same lifecycle at DRAFT and are indistinguishable
 * from here on, other than the autoGenerated flag retained for reporting.
 */
@Service
@RequiredArgsConstructor
public class PurchaseOrderService {

    private final PurchaseOrderRepository purchaseOrderRepository;
    private final SupplierRepository supplierRepository;
    private final IngredientRepository ingredientRepository;
    private final UserRepository userRepository;
    private final PdfExportService pdfExportService;

    /** DRAFT -> PENDING_APPROVAL -> APPROVED -> ORDERED -> RECEIVED -> CANCELLED. */
    private static final Map<PurchaseOrderStatus, PurchaseOrderStatus> NEXT = Map.of(
            PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.PENDING_APPROVAL,
            PurchaseOrderStatus.PENDING_APPROVAL, PurchaseOrderStatus.APPROVED,
            PurchaseOrderStatus.APPROVED, PurchaseOrderStatus.ORDERED
    );

    private static final List<PurchaseOrderStatus> ACTIONABLE_STATUSES = List.of(
            PurchaseOrderStatus.DRAFT, PurchaseOrderStatus.PENDING_APPROVAL,
            PurchaseOrderStatus.APPROVED, PurchaseOrderStatus.ORDERED
    );

    // DTO mapping happens INSIDE these @Transactional methods, not in the controller -
    // PurchaseOrder.supplier and PurchaseOrderItem.ingredient are lazy-fetched and this
    // project deliberately runs with open-in-view: false (see application.yml and the
    // identical fix in IngredientService), so touching them after the session closes
    // throws LazyInitializationException. findByStatus happened to dodge this via its
    // @EntityGraph, but advance()/cancel() did not - both used a plain findById.

    @Transactional(readOnly = true)
    public List<PurchaseOrderResponse> findByStatus(PurchaseOrderStatus status) {
        return purchaseOrderRepository.findByStatus(status).stream()
                .map(PurchaseOrderResponse::from).collect(Collectors.toList());
    }

    /** Appendix B.4 - "export them as PDF documents for email to suppliers". */
    @Transactional(readOnly = true)
    public byte[] generatePdf(Long id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Purchase order not found: " + id));
        return pdfExportService.renderPurchaseOrder(PurchaseOrderResponse.from(po));
    }

    /** Manager Dashboard PO approval panel: every PO still awaiting some action, oldest first. */
    @Transactional(readOnly = true)
    public List<PurchaseOrderResponse> findActionable() {
        return purchaseOrderRepository.findByStatusIn(ACTIONABLE_STATUSES).stream()
                .sorted(Comparator.comparing(PurchaseOrder::getCreatedAt))
                .map(PurchaseOrderResponse::from)
                .collect(Collectors.toList());
    }

    @Transactional
    @AuditableAction("PURCHASE_ORDER_CREATED")
    public PurchaseOrderResponse createManual(CreatePurchaseOrderRequest request) {
        Supplier supplier = supplierRepository.findById(request.supplierId())
                .orElseThrow(() -> new ResourceNotFoundException("Supplier not found: " + request.supplierId()));

        PurchaseOrder po = PurchaseOrder.builder()
                .supplier(supplier)
                .status(PurchaseOrderStatus.DRAFT)
                .autoGenerated(false)
                .build();

        for (PurchaseOrderItemRequest itemRequest : request.items()) {
            Ingredient ingredient = ingredientRepository.findById(itemRequest.ingredientId())
                    .orElseThrow(() -> new ResourceNotFoundException("Ingredient not found: " + itemRequest.ingredientId()));

            po.getItems().add(PurchaseOrderItem.builder()
                    .purchaseOrder(po)
                    .ingredient(ingredient)
                    .quantityOrdered(itemRequest.quantityOrdered())
                    .estimatedUnitCost(itemRequest.estimatedUnitCost() != null
                            ? itemRequest.estimatedUnitCost() : ingredient.getAverageUnitCost())
                    .build());
        }

        return PurchaseOrderResponse.from(purchaseOrderRepository.save(po));
    }

    /**
     * Advances exactly one step forward. Approval additionally stamps the approving
     * manager - required for the FR-30 approval audit trail.
     */
    @Transactional
    @AuditableAction("PURCHASE_ORDER_ADVANCED")
    public PurchaseOrderResponse advance(Long id, Long actingUserId) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Purchase order not found: " + id));

        PurchaseOrderStatus next = NEXT.get(po.getStatus());
        if (next == null) {
            throw new InvalidOrderStateException("Purchase order in status " + po.getStatus() + " cannot be advanced further");
        }

        if (next == PurchaseOrderStatus.APPROVED) {
            User approver = userRepository.findById(actingUserId)
                    .orElseThrow(() -> new ResourceNotFoundException("User not found: " + actingUserId));
            po.setApprovedBy(approver);
        }

        po.setStatus(next);
        return PurchaseOrderResponse.from(purchaseOrderRepository.save(po));
    }

    @Transactional
    @AuditableAction("PURCHASE_ORDER_CANCELLED")
    public PurchaseOrderResponse cancel(Long id) {
        PurchaseOrder po = purchaseOrderRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Purchase order not found: " + id));

        if (po.getStatus() == PurchaseOrderStatus.RECEIVED) {
            throw new InvalidOrderStateException("Cannot cancel a PO that has already been received");
        }
        po.setStatus(PurchaseOrderStatus.CANCELLED);
        return PurchaseOrderResponse.from(purchaseOrderRepository.save(po));
    }
}
