package com.rms.dto.response;

import com.rms.domain.PurchaseOrder;
import com.rms.domain.enums.PurchaseOrderStatus;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

public record PurchaseOrderResponse(
        Long id,
        String supplierName,
        PurchaseOrderStatus status,
        Boolean autoGenerated,
        LocalDateTime createdAt,
        List<PurchaseOrderItemResponse> items
) {
    public record PurchaseOrderItemResponse(String ingredientName, BigDecimal quantityOrdered, BigDecimal estimatedUnitCost) {}

    public static PurchaseOrderResponse from(PurchaseOrder po) {
        List<PurchaseOrderItemResponse> items = po.getItems().stream()
                .map(i -> new PurchaseOrderItemResponse(i.getIngredient().getName(), i.getQuantityOrdered(), i.getEstimatedUnitCost()))
                .toList();
        return new PurchaseOrderResponse(
                po.getId(), po.getSupplier().getName(), po.getStatus(), po.getAutoGenerated(), po.getCreatedAt(), items);
    }
}
