package com.rms.dto.response;

import java.math.BigDecimal;

/** Payload broadcast on /topic/alerts/stock (Admin + Manager dashboards only). */
public record StockAlertMessage(
        Long ingredientId,
        String ingredientName,
        BigDecimal currentStock,
        BigDecimal reorderLevel,
        String severity, // LOW_STOCK or OUT_OF_STOCK
        Long autoGeneratedPurchaseOrderId // null unless this breach just spawned a draft PO
) {}
