package com.rms.service;

import com.rms.domain.Ingredient;
import com.rms.domain.Supplier;
import com.rms.domain.enums.PurchaseOrderStatus;
import com.rms.domain.enums.UnitType;
import com.rms.dto.response.StockAlertMessage;
import com.rms.repository.IngredientRepository;
import com.rms.repository.PurchaseOrderRepository;
import com.rms.websocket.OrderEventPublisher;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.*;

/**
 * Unit tests for the PO-drafting/dedup logic extracted out of RecipeDeductionServiceTest
 * when reorder handling became event-driven (NFR-05 - see InventoryAlertService's class
 * comment for why this had to move behind a real re-fetch-by-id rather than staying a
 * synchronous call passed the caller's entity reference). Mirrors the substance of what
 * were UT-06/UT-07 in the dissertation Chapter 5 table, now exercised directly against
 * handleReorderBreach rather than indirectly through the deduction engine.
 */
@ExtendWith(MockitoExtension.class)
class InventoryAlertServiceTest {

    @Mock private PurchaseOrderRepository purchaseOrderRepository;
    @Mock private IngredientRepository ingredientRepository;
    @Mock private OrderEventPublisher publisher;

    private InventoryAlertService inventoryAlertService;

    private Supplier supplier;
    private Ingredient chicken;

    @BeforeEach
    void setUp() {
        inventoryAlertService = new InventoryAlertService(purchaseOrderRepository, ingredientRepository, publisher);

        supplier = Supplier.builder().id(1L).name("Colombo Seafood Traders").build();
        chicken = Ingredient.builder()
                .id(2L).name("Chicken").currentStock(new BigDecimal("80"))
                .reorderLevel(new BigDecimal("100")).unitType(UnitType.KG)
                .averageUnitCost(BigDecimal.valueOf(20)).preferredSupplier(supplier)
                .build();
    }

    @Test
    @DisplayName("UT-06: Reorder breach with no in-flight PO drafts one and publishes the alert with its id")
    void handleReorderBreach_draftsNewPo() {
        when(ingredientRepository.findById(2L)).thenReturn(Optional.of(chicken));
        when(purchaseOrderRepository.existsBySupplierIdAndStatusAndItems_Ingredient_Id(eq(1L), any(), eq(2L)))
                .thenReturn(false);
        when(purchaseOrderRepository.save(any())).thenAnswer(inv -> {
            var po = inv.getArgument(0, com.rms.domain.PurchaseOrder.class);
            po.setId(99L);
            return po;
        });

        inventoryAlertService.handleReorderBreach(2L, "LOW_STOCK");

        verify(purchaseOrderRepository).save(any());
        ArgumentCaptor<StockAlertMessage> captor = ArgumentCaptor.forClass(StockAlertMessage.class);
        verify(publisher).publishStockAlert(captor.capture());
        assertThat(captor.getValue().severity()).isEqualTo("LOW_STOCK");
        assertThat(captor.getValue().autoGeneratedPurchaseOrderId()).isEqualTo(99L);
    }

    @Test
    @DisplayName("UT-07: Reorder breach with an in-flight PO already open does not draft a duplicate")
    void handleReorderBreach_existingInFlightPo_noDuplicate() {
        when(ingredientRepository.findById(2L)).thenReturn(Optional.of(chicken));
        when(purchaseOrderRepository.existsBySupplierIdAndStatusAndItems_Ingredient_Id(eq(1L), any(), eq(2L)))
                .thenReturn(true);

        inventoryAlertService.handleReorderBreach(2L, "LOW_STOCK");

        verify(purchaseOrderRepository, never()).save(any());
        ArgumentCaptor<StockAlertMessage> captor = ArgumentCaptor.forClass(StockAlertMessage.class);
        verify(publisher).publishStockAlert(captor.capture());
        assertThat(captor.getValue().autoGeneratedPurchaseOrderId()).isNull();
    }

    @Test
    @DisplayName("An ingredient with no preferred supplier skips drafting but still publishes the alert")
    void handleReorderBreach_noPreferredSupplier_skipsDraft() {
        chicken.setPreferredSupplier(null);
        when(ingredientRepository.findById(2L)).thenReturn(Optional.of(chicken));

        inventoryAlertService.handleReorderBreach(2L, "OUT_OF_STOCK");

        verify(purchaseOrderRepository, never())
                .existsBySupplierIdAndStatusAndItems_Ingredient_Id(any(), any(), any());
        verify(purchaseOrderRepository, never()).save(any());
        ArgumentCaptor<StockAlertMessage> captor = ArgumentCaptor.forClass(StockAlertMessage.class);
        verify(publisher).publishStockAlert(captor.capture());
        assertThat(captor.getValue().autoGeneratedPurchaseOrderId()).isNull();
    }

    @Test
    @DisplayName("An ingredient deleted between the breach event firing and the handler running is a no-op")
    void handleReorderBreach_ingredientNoLongerExists_noOp() {
        when(ingredientRepository.findById(anyLong())).thenReturn(Optional.empty());

        inventoryAlertService.handleReorderBreach(999L, "LOW_STOCK");

        verifyNoInteractions(purchaseOrderRepository, publisher);
    }
}
