package com.rms.domain.enums;

public enum PurchaseOrderStatus {
    DRAFT,             // auto-generated by the reorder trigger, or created manually
    PENDING_APPROVAL,
    APPROVED,
    ORDERED,
    RECEIVED,          // fully reconciled against a GRN
    CANCELLED
}
